/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;

/**
 *
 * @author MODOFWAR
 */
public class HalLowongan extends javax.swing.JFrame {

    /**
     * Creates new form HalLowongan
     */
    public HalLowongan() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public JButton getTampilkanBerkasDiterima() {
        return tampilkanBerkasDiterima;
    }

    public JButton getTampilkanPelamarLowongan() {
        return tampilkanPelamarLowongan;
    }
    
    public JButton getTambahLowongan() {
        return tambahLowongan;
    }
    public JButton getHapusLowongan() {
        return hapusLowongan;
    }
    public JButton getCariLowongan() {
        return cariLowongan;
    }
    
    public JButton getTerimaBerkasButton() {
        return terimaBerkasButton;
    }

    public JButton getButtonBack() {
        return buttonBack;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cariLowongan = new javax.swing.JButton();
        tambahLowongan = new javax.swing.JButton();
        hapusLowongan = new javax.swing.JButton();
        tampilkanPelamarLowongan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        terimaBerkasButton = new javax.swing.JButton();
        tampilkanBerkasDiterima = new javax.swing.JButton();
        perusahaan3 = new javax.swing.JButton();
        perusahaan4 = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        perusahaan5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        cariLowongan.setBackground(new java.awt.Color(255, 102, 0));
        cariLowongan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/EEE.png"))); // NOI18N
        cariLowongan.setBorderPainted(false);

        tambahLowongan.setBackground(new java.awt.Color(255, 102, 0));
        tambahLowongan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/output-onlinepngtools.png"))); // NOI18N
        tambahLowongan.setBorderPainted(false);
        tambahLowongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahLowonganActionPerformed(evt);
            }
        });

        hapusLowongan.setBackground(new java.awt.Color(255, 102, 0));
        hapusLowongan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/CCC.png"))); // NOI18N
        hapusLowongan.setBorderPainted(false);

        tampilkanPelamarLowongan.setBackground(new java.awt.Color(255, 102, 0));
        tampilkanPelamarLowongan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/DDD.png"))); // NOI18N
        tampilkanPelamarLowongan.setBorderPainted(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/G.jpg"))); // NOI18N

        terimaBerkasButton.setBackground(new java.awt.Color(255, 102, 0));
        terimaBerkasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/gg.png"))); // NOI18N
        terimaBerkasButton.setBorderPainted(false);
        terimaBerkasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terimaBerkasButtonActionPerformed(evt);
            }
        });

        tampilkanBerkasDiterima.setBackground(new java.awt.Color(255, 102, 0));
        tampilkanBerkasDiterima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/ii.png"))); // NOI18N
        tampilkanBerkasDiterima.setBorderPainted(false);

        perusahaan3.setBackground(new java.awt.Color(255, 102, 0));
        perusahaan3.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        perusahaan3.setForeground(new java.awt.Color(255, 255, 255));
        perusahaan3.setText("VACANCY");
        perusahaan3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        perusahaan3.setBorderPainted(false);
        perusahaan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perusahaan3ActionPerformed(evt);
            }
        });

        perusahaan4.setBackground(new java.awt.Color(51, 51, 51));
        perusahaan4.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        perusahaan4.setForeground(new java.awt.Color(255, 255, 255));
        perusahaan4.setText("PERUSAHAAN");
        perusahaan4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        perusahaan4.setBorderPainted(false);
        perusahaan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perusahaan4ActionPerformed(evt);
            }
        });

        buttonBack.setBackground(new java.awt.Color(255, 255, 255));
        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/33.png"))); // NOI18N
        buttonBack.setBorderPainted(false);
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        perusahaan5.setBackground(new java.awt.Color(0, 0, 0));
        perusahaan5.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        perusahaan5.setForeground(new java.awt.Color(255, 255, 255));
        perusahaan5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        perusahaan5.setBorderPainted(false);
        perusahaan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perusahaan5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(perusahaan4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(perusahaan5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(perusahaan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(tambahLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapusLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tampilkanPelamarLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(terimaBerkasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tampilkanBerkasDiterima, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(perusahaan4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(perusahaan3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perusahaan5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tampilkanBerkasDiterima, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampilkanPelamarLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(terimaBerkasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahLowonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahLowonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahLowonganActionPerformed

    private void terimaBerkasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terimaBerkasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terimaBerkasButtonActionPerformed

    private void perusahaan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perusahaan3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perusahaan3ActionPerformed

    private void perusahaan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perusahaan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perusahaan4ActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed

    private void perusahaan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perusahaan5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perusahaan5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalLowongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalLowongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalLowongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalLowongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalLowongan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton cariLowongan;
    private javax.swing.JButton hapusLowongan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton perusahaan3;
    private javax.swing.JButton perusahaan4;
    private javax.swing.JButton perusahaan5;
    private javax.swing.JButton tambahLowongan;
    private javax.swing.JButton tampilkanBerkasDiterima;
    private javax.swing.JButton tampilkanPelamarLowongan;
    private javax.swing.JButton terimaBerkasButton;
    // End of variables declaration//GEN-END:variables
}
